Sample.Gtk: build SourceGen separately
Build Controls.SourceGen.csproj before building
Microsoft.Maui.Gtk.slnf. We have to do this since
sometimes when building the Sample.Gtk project, the error
below is shown. It's a random error that happens when
building the Microsoft.Maui.Gtk.slnf but it doesn't happen
in each build attempt.

```
CSC : error CS0006: Metadata file '/home/runner/work/maui/maui/.nuspec/Microsoft.Maui.Controls.SourceGen.dll' could not be found [/home/runner/work/maui/maui/src/Controls/samples/Controls.Sample.Gtk/Controls.Sample.Gtk.csproj]
    0 Warning(s)
    1 Error(s)
```